#!/bin/bash


SESSION_NAME="launch_bt"


cd ~/diploma_ws/
source ~/.bashrc
source install/local_setup.bash
export TURTLEBOT3_MODEL=waffle_pi
export GAZEBO_MODEL_PATH=$GAZEBO_MODEL_PATH:/opt/ros/humble/share/turtlebot3_gazebo/models


tmux new-session -d -s $SESSION_NAME
tmux split-window -v
tmux select-layout tiled

tmux send-keys -t $SESSION_NAME.0 "ros2 launch bt main_bt.launch.py" Enter
tmux send-keys -t $SESSION_NAME.1 "ros2 run groot Groot" Enter

tmux a -t $SESSION_NAME
