#!/bin/bash


SESSION_NAME="launch_system_dyn_world"


cd ~/diploma_ws/
source ~/.bashrc
source install/local_setup.bash
export TURTLEBOT3_MODEL=waffle_pi
export GAZEBO_MODEL_PATH=$GAZEBO_MODEL_PATH:/opt/ros/humble/share/turtlebot3_gazebo/models


tmux new-session -d -s $SESSION_NAME
tmux split-window -v
tmux select-layout tiled
tmux split-window -v
tmux select-layout tiled
tmux split-window -v
tmux select-layout tiled
tmux split-window -v
tmux select-layout tiled
tmux split-window -v
tmux select-layout tiled
tmux split-window -v
tmux select-layout tiled
tmux split-window -v
tmux select-layout tiled
tmux split-window -v
tmux select-layout tiled

tmux send-keys -t $SESSION_NAME.0 "ros2 launch turtlebot3_gazebo turtlebot3_dyn_obs.launch.py use_sim_time:=True" Enter
tmux send-keys -t $SESSION_NAME.1 "ros2 launch turtlebot3_navigation2 navigation2.launch.py use_sim_time:=True map:='/home/denis/diploma_ws/maps/dyn_obs.yaml'" Enter
tmux send-keys -t $SESSION_NAME.2 "ros2 run fsu lidar_remapping_node" Enter
tmux send-keys -t $SESSION_NAME.3 "ros2 run fsu imu_remapping_node" Enter
tmux send-keys -t $SESSION_NAME.4 "ros2 run fsu odom_remapping_node" Enter
tmux send-keys -t $SESSION_NAME.5 "ros2 launch ssu sensor_supervisitory_unit.launch.py" Enter
tmux send-keys -t $SESSION_NAME.6 "ros2 launch csu control_switching_unit.launch.py" Enter
tmux send-keys -t $SESSION_NAME.7 "ros2 launch bsu battery_simulation_unit.launch.py" Enter
tmux send-keys -t $SESSION_NAME.8 "ros2 launch nspu navigation_services_provider_unit.launch.py" Enter

tmux a -t $SESSION_NAME